# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import recommender_pb2 as proto_dot_recommender__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/recommender_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AnimeRecommenderStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCompatible = channel.unary_unary(
                '/recommender.AnimeRecommender/GetCompatible',
                request_serializer=proto_dot_recommender__pb2.CompatibleRequest.SerializeToString,
                response_deserializer=proto_dot_recommender__pb2.CompatibleResponse.FromString,
                _registered_method=True)
        self.GetCfRecommendations = channel.unary_unary(
                '/recommender.AnimeRecommender/GetCfRecommendations',
                request_serializer=proto_dot_recommender__pb2.CollaborativeRecommendationRequest.SerializeToString,
                response_deserializer=proto_dot_recommender__pb2.CollaborativeRecommendationResponse.FromString,
                _registered_method=True)
        self.GetCompatibility = channel.unary_unary(
                '/recommender.AnimeRecommender/GetCompatibility',
                request_serializer=proto_dot_recommender__pb2.CompatibilityRequest.SerializeToString,
                response_deserializer=proto_dot_recommender__pb2.CompatibilityResponse.FromString,
                _registered_method=True)
        self.GetCompatibilityScores = channel.unary_unary(
                '/recommender.AnimeRecommender/GetCompatibilityScores',
                request_serializer=proto_dot_recommender__pb2.CompatibilityBatchRequest.SerializeToString,
                response_deserializer=proto_dot_recommender__pb2.CompatibilityBatchResponse.FromString,
                _registered_method=True)
        self.GetRelated = channel.unary_unary(
                '/recommender.AnimeRecommender/GetRelated',
                request_serializer=proto_dot_recommender__pb2.RelatedRequest.SerializeToString,
                response_deserializer=proto_dot_recommender__pb2.RelatedResponse.FromString,
                _registered_method=True)


class AnimeRecommenderServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetCompatible(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCfRecommendations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCompatibility(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCompatibilityScores(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRelated(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnimeRecommenderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCompatible': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCompatible,
                    request_deserializer=proto_dot_recommender__pb2.CompatibleRequest.FromString,
                    response_serializer=proto_dot_recommender__pb2.CompatibleResponse.SerializeToString,
            ),
            'GetCfRecommendations': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCfRecommendations,
                    request_deserializer=proto_dot_recommender__pb2.CollaborativeRecommendationRequest.FromString,
                    response_serializer=proto_dot_recommender__pb2.CollaborativeRecommendationResponse.SerializeToString,
            ),
            'GetCompatibility': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCompatibility,
                    request_deserializer=proto_dot_recommender__pb2.CompatibilityRequest.FromString,
                    response_serializer=proto_dot_recommender__pb2.CompatibilityResponse.SerializeToString,
            ),
            'GetCompatibilityScores': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCompatibilityScores,
                    request_deserializer=proto_dot_recommender__pb2.CompatibilityBatchRequest.FromString,
                    response_serializer=proto_dot_recommender__pb2.CompatibilityBatchResponse.SerializeToString,
            ),
            'GetRelated': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRelated,
                    request_deserializer=proto_dot_recommender__pb2.RelatedRequest.FromString,
                    response_serializer=proto_dot_recommender__pb2.RelatedResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'recommender.AnimeRecommender', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('recommender.AnimeRecommender', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AnimeRecommender(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCompatible(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recommender.AnimeRecommender/GetCompatible',
            proto_dot_recommender__pb2.CompatibleRequest.SerializeToString,
            proto_dot_recommender__pb2.CompatibleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCfRecommendations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recommender.AnimeRecommender/GetCfRecommendations',
            proto_dot_recommender__pb2.CollaborativeRecommendationRequest.SerializeToString,
            proto_dot_recommender__pb2.CollaborativeRecommendationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCompatibility(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recommender.AnimeRecommender/GetCompatibility',
            proto_dot_recommender__pb2.CompatibilityRequest.SerializeToString,
            proto_dot_recommender__pb2.CompatibilityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCompatibilityScores(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recommender.AnimeRecommender/GetCompatibilityScores',
            proto_dot_recommender__pb2.CompatibilityBatchRequest.SerializeToString,
            proto_dot_recommender__pb2.CompatibilityBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRelated(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recommender.AnimeRecommender/GetRelated',
            proto_dot_recommender__pb2.RelatedRequest.SerializeToString,
            proto_dot_recommender__pb2.RelatedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
