# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: recommender_health.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'recommender_health.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18recommender_health.proto\x12\x0brecommender\"\x14\n\x12HealthCheckRequest\"\xb1\x01\n\x13HealthCheckResponse\x12;\n\x13\x61nime_loader_status\x18\x01 \x01(\x0b\x32\x1e.recommender.AnimeLoaderStatus\x12\x34\n\x10\x64\x61ta_sets_status\x18\x02 \x01(\x0b\x32\x1a.recommender.DataSetStatus\x12\x0f\n\x07version\x18\x03 \x01(\x05\x12\x16\n\x0eservice_status\x18\x04 \x01(\t\"\xbb\x01\n\x11\x41nimeLoaderStatus\x12\x11\n\tis_loaded\x18\x01 \x01(\x08\x12\x11\n\thas_error\x18\x02 \x01(\x08\x12\x13\n\x0b\x61nime_count\x18\x03 \x01(\x05\x12\x15\n\rerror_message\x18\x04 \x01(\t\x12\x12\n\ncache_hits\x18\x05 \x01(\x05\x12\x14\n\x0c\x63\x61\x63he_misses\x18\x06 \x01(\x05\x12\x12\n\ncache_size\x18\x07 \x01(\x05\x12\x16\n\x0e\x63\x61\x63he_max_size\x18\x08 \x01(\x05\"P\n\rDataSetStatus\x12\x12\n\nis_healthy\x18\x01 \x01(\x08\x12+\n\nset_status\x18\x02 \x03(\x0b\x32\x17.recommender.DataHealth\"*\n\nDataHealth\x12\x0c\n\x04\x66ile\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t2j\n\x16\x41nimeRecommenderHealth\x12P\n\x0bHealthCheck\x12\x1f.recommender.HealthCheckRequest\x1a .recommender.HealthCheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'recommender_health_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTHCHECKREQUEST']._serialized_start=41
  _globals['_HEALTHCHECKREQUEST']._serialized_end=61
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=64
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=241
  _globals['_ANIMELOADERSTATUS']._serialized_start=244
  _globals['_ANIMELOADERSTATUS']._serialized_end=431
  _globals['_DATASETSTATUS']._serialized_start=433
  _globals['_DATASETSTATUS']._serialized_end=513
  _globals['_DATAHEALTH']._serialized_start=515
  _globals['_DATAHEALTH']._serialized_end=557
  _globals['_ANIMERECOMMENDERHEALTH']._serialized_start=559
  _globals['_ANIMERECOMMENDERHEALTH']._serialized_end=665
# @@protoc_insertion_point(module_scope)
